# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#8ea4a2" }

# Find
find_keyword  = { fg = "#c4b28a", bold = true, italic = true, underline = true }
find_position = { fg = "#a292a3", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#8a9a7b", bg = "#8a9a7b" }
marker_cut      = { fg = "#c4746e", bg = "#c4746e" }
marker_marked   = { fg = "#8ea4a2", bg = "#8ea4a2" }
marker_selected = { fg = "#c4b28a", bg = "#c4b28a" }

# Count
count_copied   = { fg = "#181616", bg = "#8a9a7b" }
count_cut      = { fg = "#181616", bg = "#c4746e" }
count_selected = { fg = "#181616", bg = "#c4b28a" }

# Border
border_symbol = "│"
border_style  = { fg = "#737c73" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#181616", bg = "#658594", bold = true }
inactive = { fg = "#658594", bg = "#1d1c19" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#181616", bg = "#658594", bold = true }
normal_alt  = { fg = "#658594", bg = "#1d1c19" }

# Select mode
select_main = { fg = "#181616", bg = "#8ea4a2", bold = true }
select_alt  = { fg = "#8ea4a2", bg = "#1d1c19" }

# Unset mode
unset_main = { fg = "#181616", bg = "#b6927b", bold = true }
unset_alt  = { fg = "#b6927b", bg = "#1d1c19" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#737c73" }
perm_type  = { fg = "#658594" }
perm_read  = { fg = "#c4b28a" }
perm_write = { fg = "#c4746e" }
perm_exec  = { fg = "#8a9a7b" }

# Progress
progress_label  = { fg = "#c5c9c5", bold = true }
progress_normal = { fg = "#8a9a7b", bg = "#282727" }
progress_error  = { fg = "#c4b28a", bg = "#c4746e" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#658594" }
active   = { fg = "#a292a3", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#658594" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#658594" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#658594" }
title   = {}
hovered = { fg = "#a292a3", bold = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#1d1c19" }
cand            = { fg = "#8ea4a2" }
rest            = { fg = "#7a8382" }
desc            = { fg = "#a292a3" }
separator       = "  "
separator_style = { fg = "#393836" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#8ea4a2" }
run     = { fg = "#a292a3" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#1d1c19", bg = "#c5c9c5" }

# : }}}


# : Spotter {{{

[spot]
border   = { fg = "#658594" }
title    = { fg = "#658594" }
tbl_col  = { fg = "#8ea4a2" }
tbl_cell = { fg = "#a292a3", bg = "#282727" }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#8a9a7b" }
title_warn  = { fg = "#c4b28a" }
title_error = { fg = "#c4746e" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Image
	{ mime = "image/*", fg = "#8ea4a2" },
	# Media
	{ mime = "{audio,video}/*", fg = "#c4b28a" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#a292a3" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#8a9a7b" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#7a8382" },
	# Fallback
	{ url = "*", fg = "#c5c9c5" },
	{ url = "*/", fg = "#658594" },
]

# : }}}

[icon]

dirs = [
	{ name = ".config", text = "", fg = "#a292a3" },
	{ name = ".git", text = "", fg = "#8ea4a2" },
	{ name = ".github", text = "", fg = "#658594" },
	{ name = ".npm", text = "", fg = "#658594" },
	{ name = "Desktop", text = "", fg = "#8ea4a2" },
	{ name = "Development", text = "", fg = "#8ea4a2" },
	{ name = "Documents", text = "", fg = "#8ea4a2" },
	{ name = "Downloads", text = "", fg = "#8ea4a2" },
	{ name = "Library", text = "", fg = "#8ea4a2" },
	{ name = "Movies", text = "", fg = "#8ea4a2" },
	{ name = "Music", text = "", fg = "#8ea4a2" },
	{ name = "Pictures", text = "", fg = "#8ea4a2" },
	{ name = "Public", text = "", fg = "#8ea4a2" },
	{ name = "Videos", text = "", fg = "#8ea4a2" },
]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#c5c9c5" },
	{ if = "link", text = "", fg = "#737c73" },
	{ if = "block", text = "", fg = "#b6927b" },
	{ if = "char", text = "", fg = "#b6927b" },
	{ if = "fifo", text = "", fg = "#b6927b" },
	{ if = "sock", text = "", fg = "#b6927b" },
	{ if = "sticky", text = "", fg = "#b6927b" },
	{ if = "dummy", text = "", fg = "#c4746e" },

	# Fallback
	{ if = "dir & hovered", text = "", fg = "#658594" },
	{ if = "dir", text = "", fg = "#658594" },
	{ if = "exec", text = "", fg = "#8a9a7b" },
	{ if = "!dir", text = "", fg = "#c5c9c5" },
]
