# Kanagawa Dragon (near-black)
set -gq @thm_bg "#181616"
set -gq @thm_fg "#c5c9c5"
set -gq @thm_rosewater "#c4b28a"
set -gq @thm_flamingo "#b6927b"
set -gq @thm_pink "#a292a3"
set -gq @thm_mauve "#8992a7"
set -gq @thm_red "#c4746e"
set -gq @thm_maroon "#c4746e"
set -gq @thm_peach "#b6927b"
set -gq @thm_yellow "#c4b28a"
set -gq @thm_green "#8a9a7b"
set -gq @thm_teal "#8ea4a2"
set -gq @thm_sky "#949fb5"
set -gq @thm_sapphire "#8ba4b0"
set -gq @thm_blue "#658594"
set -gq @thm_lavender "#949fb5"
set -gq @thm_subtext_1 "#a6a69c"
set -gq @thm_subtext_0 "#c8c093"
set -gq @thm_overlay_2 "#7a8382"
set -gq @thm_overlay_1 "#737c73"
set -gq @thm_overlay_0 "#625e5a"
set -gq @thm_surface_2 "#393836"
set -gq @thm_surface_1 "#282727"
set -gq @thm_surface_0 "#1d1c19"
set -gq @thm_mantle "#12120f"
set -gq @thm_crust "#0d0c0c"
