# Kanagawa Wave (default dark)
set -gq @thm_bg "#1f1f28"
set -gq @thm_fg "#dcd7ba"
set -gq @thm_rosewater "#e6c384"
set -gq @thm_flamingo "#ffa066"
set -gq @thm_pink "#d27e99"
set -gq @thm_mauve "#957fb8"
set -gq @thm_red "#e46876"
set -gq @thm_maroon "#ff5d62"
set -gq @thm_peach "#ffa066"
set -gq @thm_yellow "#e6c384"
set -gq @thm_green "#98bb6c"
set -gq @thm_teal "#7aa89f"
set -gq @thm_sky "#a3d4d5"
set -gq @thm_sapphire "#7fb4ca"
set -gq @thm_blue "#7e9cd8"
set -gq @thm_lavender "#9cabca"
set -gq @thm_subtext_1 "#9cabca"
set -gq @thm_subtext_0 "#c8c093"
set -gq @thm_overlay_2 "#938aa9"
set -gq @thm_overlay_1 "#727169"
set -gq @thm_overlay_0 "#54546d"
set -gq @thm_surface_2 "#363646"
set -gq @thm_surface_1 "#2a2a37"
set -gq @thm_surface_0 "#1a1a22"
set -gq @thm_mantle "#181820"
set -gq @thm_crust "#16161d"
