# Tokyonight Day (light)
set -gq @thm_bg "#e1e2e7"
set -gq @thm_fg "#3760bf"
set -gq @thm_rosewater "#2e5857"
set -gq @thm_flamingo "#c64343"
set -gq @thm_pink "#9854f1"
set -gq @thm_mauve "#7847bd"
set -gq @thm_red "#f52a65"
set -gq @thm_maroon "#c64343"
set -gq @thm_peach "#b15c00"
set -gq @thm_yellow "#8c6c3e"
set -gq @thm_green "#587539"
set -gq @thm_teal "#118c74"
set -gq @thm_sky "#188092"
set -gq @thm_sapphire "#07879d"
set -gq @thm_blue "#2e7de9"
set -gq @thm_lavender "#006a83"
set -gq @thm_subtext_1 "#68709a"
set -gq @thm_subtext_0 "#6172b0"
set -gq @thm_overlay_2 "#68709a"
set -gq @thm_overlay_1 "#848cb5"
set -gq @thm_overlay_0 "#8990b3"
set -gq @thm_surface_2 "#a1a6c5"
set -gq @thm_surface_1 "#a8aecb"
set -gq @thm_surface_0 "#c4c8da"
set -gq @thm_mantle "#d0d5e3"
set -gq @thm_crust "#c1c9df"
