# Tokyonight Moon
set -gq @thm_bg "#222436"
set -gq @thm_fg "#c8d3f5"
set -gq @thm_rosewater "#b4f9f8"
set -gq @thm_flamingo "#c53b53"
set -gq @thm_pink "#c099ff"
set -gq @thm_mauve "#fca7ea"
set -gq @thm_red "#ff757f"
set -gq @thm_maroon "#c53b53"
set -gq @thm_peach "#ff966c"
set -gq @thm_yellow "#ffc777"
set -gq @thm_green "#c3e88d"
set -gq @thm_teal "#4fd6be"
set -gq @thm_sky "#65bcff"
set -gq @thm_sapphire "#0db9d7"
set -gq @thm_blue "#82aaff"
set -gq @thm_lavender "#89ddff"
set -gq @thm_subtext_1 "#737aa2"
set -gq @thm_subtext_0 "#828bb8"
set -gq @thm_overlay_2 "#737aa2"
set -gq @thm_overlay_1 "#636da6"
set -gq @thm_overlay_0 "#545c7e"
set -gq @thm_surface_2 "#444a73"
set -gq @thm_surface_1 "#3b4261"
set -gq @thm_surface_0 "#2f334d"
set -gq @thm_mantle "#1e2030"
set -gq @thm_crust "#191b29"
